version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springboot-demo
      MYSQL_USER: springboot-demo
      MYSQL_PASSWORD: springboot-demo
    ports:
    - 3306:3306