server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          yconnect:
            provider:                     "yconnect"
            client-name:                  "Yahoo! Japan"
            client-id:                    "[env]"
            client-secret:                "[env]"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid 
              - profile 
              - email
              - address
        provider: 
          yconnect:
            authorization-uri:   "https://auth.login.yahoo.co.jp/yconnect/v2/authorization"
            token-uri:           "https://auth.login.yahoo.co.jp/yconnect/v2/token"
            jwk-set-uri:         "https://auth.login.yahoo.co.jp/yconnect/v2/jwks"
            user-info-uri:       "https://userinfo.yahooapis.jp/yconnect/v2/attribute"
            user-name-attribute: "sub"
  profiles:
    active:
    - dev

  datasource:
    url:      "jdbc:mysql://localhost:3306/springboot-demo"
    username: "springboot-demo"
    password: "springboot-demo"

  flyway:
    encoding: UTF-8
    ignore-ignored-migrations: true
    ignore-future-migrations: false
    ignore-missing-migrations: false
  thymeleaf:    cache: false

logging:
  level:
    root: WARN
    com.example.spring.yconnect: DEBUG
